### ISSUE TITLE
Skip repeated content

### ISSUE THREAD

**Issue by tabitagreen** [carleton/reason_package#178]
Issue noted by Siteimprove.

As a user, I need a means of bypassing blocks of content that are repeated on multiple web pages.

How to fix it: One of the ways to ensure this is to have a link at the top of each page that goes directly to the main content area. (The link should be the first focusable control on the web page and be visible when it receives focus). Such a link is not present on the page. If you have not ensured this by providing this type of links or by other means, this criterion is failed. Another way of ensuring conformance is to provide a heading for each block of content that are repeated on multiple web pages.

**Comment by mryand** [comment]
Here is a page covering this topic: http://accessibility.psu.edu/skipnav/

In my work on the backend I've used this pattern. It keeps the skip link hidden from sight (but readable by screenreaders) until the link is focused in some way (typically via keyboard). When focused the link becomes visible, which makes this affordance useful to sighted users who use the keyboard (e.g. those who can't use a mouse).

HTML (first thing in body):
```html
<a href="#adminWrap" class="skipLink">Skip to main content</a>
```
CSS:
```css
a.skipLink {
	position:absolute;
	left:-9999px;
	background:#fff;
	padding:5px 10px;
}
a.skipLink:focus, a.skipLink:active, a.skipLink:hover {
	left:0;
}
```
